config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#top"
  post '/callback' => 'linebot#callback'

  resources :lists do 
    resources :words, only: [:new, :create, :edit, :update, :destroy]
  end

  patch "word/update_status" => "words#update_status", as: "update_status"

  resource :word_tests, only: [:index]
  get "word_test/result" => "word_tests#result", as: "test_result"

  get "users/config" => "users#app_config", as: "app_config"
  patch "users/config" => "users#update", as: "user"
end

app/models/list.rb
class List < ApplicationRecord
  has_many :words, dependent: :destroy
  belongs_to :user

  validates :title, presence: true

  def last_update
    time = self.updated_at
    if self.words.present?
      if time < self.words.maximum("updated_at")
        time = self.words.maximum("updated_at")
      end
    end
    
    return time
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def new
    @list = List.new
  end

  def index
    @lists = current_user.lists.sort{|a, b| b.last_update <=> a.last_update}
  end

  def create
    @list = current_user.lists.new(list_params)
    @list.save
    if current_user.question_list_id.nil?
      current_user.update(question_list_id: @list.id)
    end
  end

  def show
    @words = @list.words.order(id: "ASC")
  end

  def edit
  end

  def update
    if @list.title == params[:list][:title]
      @list.touch
    else
      @list.update(list_params)
    end
  end

  def destroy
    @list_id = @list.id
    @list.destroy
    if @list_id == current_user.question_list_id
      current_user.update(question_list_id: nil)
    end
  end

  private
  def list_params
    params.require(:list).permit(:title)
  end

  def set_list
    @list = List.find(params[:id])
  end

  def check_user
    unless @list.user == current_user
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_edit_form.html.slim
= form_with model: list, class: "w-100 d-flex align-items-center edit-form", remote: true do |f|
  .col-6
    = f.text_field :title, class: "form-control"

  .col-6
    = f.button :type => "submit", class: "submit-link mr-3" do
      i.fas.fa-check.submit-link-item
    = link_to "", lists_path, class: "back-link fas fa-times text-danger text-decoration-none mr-3"
    = link_to "", list_path(list), method: :delete, remote: true, class: "text-danger text-decoration-none far fa-trash-alt", data:{confirm: "「#{list.title}」に登録した情報がすべて削除されます。\n削除してよろしいですか？"}
    

app/views/lists/_form.html.slim
.form.mb-4
  .row
    .col-10
      = form_with model: list, remote: true, class: "input-group" do |f|
          = f.text_field :title, class: "form-control"
          = f.submit '作成', class: "input-group-append btn btn-success"
    .col-2

app/views/lists/_one_record.html.slim
.row.border-bottom.border-top.item id="list-#{list.id}"
  = link_to list_path(list), class: "col-9 text-decoration-none text-dark" do
    .row
      .col-6
        = list.title
      .col-6
        = list.words.count.to_s + " words"
  .col-3
    a.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
      span.btn.btn-sm.btn-outline-secondary
        i.fas.fa-ellipsis-h
    .dropdown-menu
      = link_to "編集", edit_list_path(list), remote: true, class: "dropdown-item text-decoration-none"
      = link_to "削除", list_path(list), method: :delete, remote: true, class: "text-danger text-decoration-none dropdown-item", data:{confirm: "「#{list.title}」に登録した情報がすべて削除されます。\n削除してよろしいですか？"}

app/views/lists/create.js.erb
<% if @list.errors.any? %>
  $("<%= j(render 'form', list: @list)%>").replaceAll(".form")
  $(".form").css('display', 'block')
  $("#list_title").unwrap()
  $("#list_title").addClass("is-invalid")
<% else %>
  $(".form").fadeOut().remove();
  $(".lists").prepend("<%= j(render 'one_record', list: @list) %>");
  $("#list-<%= @list.id %>").css('transition', 'background-color 1s');
  $("#list-<%= @list.id %>").addClass('highlight');
  $(".back-btn").css('display', 'none');
  $(".new-list-btn").fadeIn();

  setTimeout(function() {
		$("#list-<%= @list.id %>").removeClass('highlight');
	}, 50);
  setTimeout(function() {
		$("#list-<%= @list.id %>").css('transition', 'background-color 0s');
	}, 1000);
<% end %>

app/views/lists/destroy.js.erb
$("#list-<%= @list.id %>").css('backgroundcolor', '#add8e6');
$("#list-<%= @list.id %>").fadeOut();

app/views/lists/edit.js.erb
$("#list-<%= @list.id %>").html("<%= j(render 'edit_form', list: @list) %>")

app/views/lists/index.html.slim
.title.mb-4
  h3.d-inline
    | Myリスト
  .form-display-links.d-inline
    = link_to "", new_list_path, remote: true, class: "new-list-btn text-decoration-none ml-5 fas fa-plus-circle"
    = link_to "", "#", remote: true, class: "back-btn text-decoration-none ml-5 fas fa-times"

.lists
  - if @lists.present?
    - @lists.each do |list|
      .row.border-bottom.border-top.item id="list-#{list.id}"
        = link_to list_path(list), class: "col-9 text-decoration-none text-dark" do
          .row
            .col-6
              = list.title
            .col-6
              = list.words.count.to_s + " words"
        .col-3
          a.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
            span.btn.btn-sm.btn-outline-secondary
              i.fas.fa-ellipsis-h
          .dropdown-menu
            = link_to "編集", edit_list_path(list), remote: true, class: "dropdown-item text-decoration-none"
            = link_to "削除", list_path(list), method: :delete, remote: true, class: "text-danger text-decoration-none dropdown-item", data:{confirm: "「#{list.title}」に登録した情報がすべて削除されます。\n削除してよろしいですか？"}
  - else
    p 
    | リストがありません

app/views/lists/new.js.erb
$(".lists").before("<%= j(render 'form', list: @list)%>");
$(".form").slideDown('fast');
$(".new-list-btn").css('display', 'none')
$(".back-btn").fadeIn();

app/views/lists/show.html.slim
.words
  .title.mb-4
    h3.d-inline-block
      = @list.title

    .links.d-inline
      = link_to " 単語登録", new_list_word_path(@list), class: "fas fa-pen-nib text-decoration-none float-right text-success"
      
  .container
    .row.word.font-weight-bold.bg-light
      .col-2.border.border-right-0
      .col-5.border.d-flex.align-items-center
        | English 
      .col-5.border.border-left-0.d-flex.align-items-center
        | 日本語訳

    - @words.each do |word|
      .row.word id="word-#{word.id}"
        .col-2.border.border-top-0.border-right-0.d-flex.align-items-center.justify-content-center
          = check_box(word, :is_remembered, class: "word-checkbox", name: word.id, checked: word.is_remembered)
        .col-5.border.border-top-0.d-flex.align-items-center.justify-content-between
          = word.english
          span
            = link_to "", edit_list_word_path(@list, word), remote: true, class: "far fa-edit text-light"
        .col-5.border.border-top-0.border-left-0.d-flex.align-items-center.justify-content-between
          = word.japanese 
          span
            = link_to "", edit_list_word_path(@list, word), remote: true, class: "far fa-edit text-light"

app/views/lists/update.js.erb
<% if @list.errors.any? %>
  $("#list-<%= @list.id %>").html("<%= j(render 'edit_form', list: @list) %>")
  $("#list_title").addClass("is-invalid")
<% else %>
  $("#list-<%= @list.id %>").remove()
  $(".lists").prepend("<%= j(render 'one_record', list: @list) %>")
  $("#list-<%= @list.id %>").css('transition', 'background-color 1s');
  $("#list-<%= @list.id %>").addClass('highlight');

  setTimeout(function() {
		$("#list-<%= @list.id %>").removeClass('highlight');
	}, 50);
  setTimeout(function() {
		$("#list-<%= @list.id %>").css('transition', 'background-color 0s');
	}, 1000);

<% end %>