config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#top"
  post '/callback' => 'linebot#callback'

  resources :lists do 
    resources :words, only: [:new, :create, :edit, :update, :destroy]
  end

  patch "word/update_status" => "words#update_status", as: "update_status"

  resource :word_tests, only: [:index]
  get "word_test/result" => "word_tests#result", as: "test_result"

  get "users/config" => "users#app_config", as: "app_config"
  patch "users/config" => "users#update", as: "user"
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :list
  has_many :questions

  validates :english, presence: true
  validates :japanese, presence: true
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:new, :create, :edit, :update]
  before_action :check_user, only: [:new]
  before_action :set_word, only: [:edit, :update, :update_status, :destroy]


  def new
    @form = Form::WordCollection.new
  end

  def create
    @form = Form::WordCollection.new(word_collection_params)
    if @form.save_for(@list.id)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @word.update(word_params)
  end

  def update_status
    if @word.is_remembered
      @word.update(is_remembered: false)
    else
      @word.update(is_remembered: true)
    end
  end

  def destroy
    @word_id = @word.id
    @word.destroy
  end

  private
  def word_collection_params
      params.require(:form_word_collection).permit(words_attributes: [:japanese, :english])
  end

  def word_params
    params.require(:word).permit(:japanese, :english)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def check_user
    unless @list.user == current_user
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_edit_form.html.slim
= form_with model: [list, word], remote: true, class: "edit-word-form d-block w-100 align-items-center" do |f|
  .container.h-100
    .row.h-100
      .col-2.border.border-top-0.border-right-0.d-flex.align-items-center.justify-content-center
        = f.button :type => "submit", class: 'submit-link mr-2' do
          i.fas.fa-check
        = link_to "", list_path(list), class: "text-danger fas fa-times text-decoration-none mr-2 back-link"
        = link_to "", list_word_path(list, word), method: :delete, remote: true, class: "far fa-trash-alt text-danger"

      .col-5.border.border-top-0.d-flex.align-items-center
        = f.text_field :english, class: "form-control h-100"

      .col-5.border.border-top-0.border-left-0.d-flex.align-items-center
        = f.text_field :japanese, class: "form-control h-100"
    

app/views/words/_one_word.html.slim
.container
  .row.word id="word-#{word.id}"
    .col-2.border.border-top-0.border-right-0.d-flex.align-items-center.justify-content-center.updated
      = check_box(word, :is_remembered, class: "word-checkbox", name: word.id, checked: word.is_remembered)
    .col-5.border.border-top-0.d-flex.align-items-center.justify-content-between
      = word.english
      span
        = link_to "", edit_list_word_path(list, word), remote: true, class: "far fa-edit text-light"
    .col-5.border.border-top-0.border-left-0.d-flex.align-items-center.justify-content-between
      = word.japanese 
      span
          = link_to "", edit_list_word_path(list, word), remote: true, class: "far fa-edit text-light"

app/views/words/_update_table.html.slim
.container
  .row id="word-#{word.id}"
    .col-2.border.border-top-0.border-right-0
      = word.is_remembered
    .col-5.border.border-top-0
      = word.english
      span.d-inlile-block.float-right
        = link_to "", edit_list_word_path(list, word), remote: true, class: "far fa-edit text-light"
    .col-5.border.border-top-0.border-left-0
      = word.japanese 
      span.d-inlile-block.float-right
          = link_to "", edit_list_word_path(list, word), remote: true, class: "far fa-edit text-light"

app/views/words/destroy.js.erb
$("#word-<%= @word_id %>").remove()

app/views/words/edit.js.erb
$("#word-<%= @word.id %>").html("<%= j(render 'edit_form', list: @list, word: @word)%>")

app/views/words/new.html.slim
.new-words
  .title.mb-4
    h3.d-inline-block
      | 新規単語登録

    = link_to " 戻る", list_path(@list), class: "d-inline-block float-right fas fa-reply text-decoration-none"

  .new-words-form
    .d-flex.align-items-center.text-center.font-weight-bold.bg-light style="height: 45px;"
      .d-block.flex-fill.border-right.w-50
        span
          | 英単語
      .d-block.flex-fill.w-50
        span
          | 日本語訳
    = form_with model: [@list, @form], url: list_words_path, local: true do |form|
      = form.fields_for :words do |f|
        .form-inline
          = f.text_field :english, class: "form-control word-form flex-fill"
          = f.text_field :japanese, class: "form-control word-form flex-fill"

      = form.submit "登録", class: "btn btn-success btn-block"

app/views/words/update.js.erb
$("#word-<%= @word.id %>").html("<%= j(render 'one_word', word: @word, list: @list)%>")

$('.updated input[class="word-checkbox"]').change(function(){
  var word_id = $(this).attr('name'); //チェックボックスのname属性
  $.ajax({ //ajax通信
    url: '/word/update_status', 
    type: 'PATCH',
    data: {
      id: word_id  //prams[:id] に格納
    },
    dataType: 'json' //データはjson形式
  });
});