config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "homes#top"
  post '/callback' => 'linebot#callback'

  resources :lists do 
    resources :words, only: [:new, :create, :edit, :update, :destroy]
  end

  patch "word/update_status" => "words#update_status", as: "update_status"

  resource :word_tests, only: [:index]
  get "word_test/result" => "word_tests#result", as: "test_result"

  get "users/config" => "users#app_config", as: "app_config"
  patch "users/config" => "users#update", as: "user"
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | えいごろう
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      nav.navbar.navbar-expand-lg.navbar-light.bg-light
        .container
          - if user_signed_in?
            = link_to "えいごろう", lists_path, class: "navbar-brand"

            buttun.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation"
              span.navbar-toggler-icon
                span
                span 
                span
            
            .navbar-collapse.collapse#navbarNavDropdown
              ul.navbar-nav.ml-auto
                - if user_signed_in?
                  li.nav-item
                    = link_to " Myリスト" , lists_path, class: "nav-link fas fa-list"
                  li.nav-item
                    = link_to " 設定", app_config_path, class: "nav-link fas fa-cog"
          - else
            = link_to "えいごろう", root_path, class: "navbar-brand"
            ul.navbar-nav.ml-auto
              li
                = link_to " Log in", new_user_session_path, class: 'nav-link fas fa-user'

    main
      .container
        = yield